version: "2"

services:

  php:
    build: ./config/docker/php
    volumes:
      - ./app:/app
  
  web:
    image: "nginx"
    volumes: 
      - ./app:/app
      - ./config/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8005:80"
    links:
      - "php"
    command: "chmod -R 777 /app"

  composer:
    image: "composer"
    command: "composer install"
    volumes:
      - ./app:/app